name: Auto Assign Issues
on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1.1.0
        with:
          assignees: jdemelo,paulnawat,pzhou-splunk,rgil-splunk
